version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs: 
  build: 
    docker:       
      - image: circleci/node:12.13.1    
    working_directory: ~/repo
    steps:      
      - checkout
      - run: npm cache clean --force
      - run: npm install
      - run: CI=false npm run build
      - run:
          name: git conf
          command: |
            git config --global user.email "slimani.ibr@gmail.com"
            git config --global user.name "Slimani-Ibrahim"
      - add_ssh_keys:
          fingerprints:
            - "de:f0:9d:4f:8e:80:db:cf:b0:c6:65:7b:89:2b:1e:54"
      - run: npm run deploy